# Generated by Django 2.2.7 on 2019-11-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191107_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images/products/'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='gluten_status',
            field=models.NullBooleanField(choices=[(None, 'Unknown'), (True, 'Exists'), (False, 'Does not exists')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='gluten_status',
            field=models.NullBooleanField(choices=[(None, 'Unknown'), (True, 'Exists'), (False, 'Does not exists')]),
        ),
    ]
