# Generated by Django 2.2.7 on 2019-11-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_suppliertype_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='suppliers',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='data',
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default=None, upload_to='products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evidence',
            name='gluten_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Yok'), (1, 'Büyük İhtimalle Yok'), (2, 'Belirsiz'), (3, 'Küçük İhtimalle Var'), (3, 'Büyük İhtimalle Var')], default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='gluten_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Yok'), (1, 'Büyük İhtimalle Yok'), (2, 'Belirsiz'), (3, 'Küçük İhtimalle Var'), (3, 'Büyük İhtimalle Var')], default=3),
            preserve_default=False,
        ),
    ]
