# Generated by Django 2.2.7 on 2019-11-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20191113_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='gluten_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Yok'), (1, 'Büyük İhtimalle Yok'), (2, 'Belirsiz'), (3, 'Büyük İhtimalle Var'), (4, 'Var')], default=2),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='photo',
            field=models.ImageField(upload_to='kanitlar/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gluten_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Yok'), (1, 'Büyük İhtimalle Yok'), (2, 'Belirsiz'), (3, 'Büyük İhtimalle Var'), (4, 'Var')], default=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='urunler/'),
        ),
    ]
