# Generated by Django 2.2.7 on 2019-11-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20191115_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obtainmethod',
            name='data',
        ),
    ]
