# Generated by Django 2.2.7 on 2019-11-13 07:37

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20191113_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliertype',
            name='fields',
            field=django_mysql.models.JSONField(default=list),
        ),
    ]
