# Generated by Django 2.2.7 on 2019-11-13 09:08

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_suppliertype_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObtainMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='obtain_methods',
            field=models.ManyToManyField(to='product.ObtainMethod'),
        ),
    ]
