# Generated by Django 2.2.7 on 2019-11-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20191113_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='obtain_methods',
        ),
        migrations.AddField(
            model_name='obtainmethod',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='evidences',
            field=models.ManyToManyField(blank=True, to='product.Evidence'),
        ),
    ]
